spring.application.name=zadsoft

# H2 Database settings (default)
spring.datasource.url=jdbc:h2:mem:budgetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console configuration (Local only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Date formatting serialization
spring.jackson.serialization.write-dates-as-timestamps=false

# Swagger UI configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# CORS Allowed Origins
app.cors.allowed-origins=http://localhost:8080
